#!/bin/bash

# This is a script to install the new bash config file design.
# It will not destroy any data but may move ~/.bash_profile
# and ~/.bashrc aside.

now=$(date +%F)

echo "This will install the 'BASHRC' config files to $HOME"
echo "It will not destroy any files but might move ~/.bash_profile"
echo "to ~/.bash_profile.$now and ~/.bashrc to ~/.bashrc.$now."
echo "You may also need to debug the resulting configuration."
echo
echo -n "Do you want to continue? [Y/n] "
read resp
if [[ -n "$resp" && "$resp" != [yY]* ]]; then
    exit 0
fi

if [[ -w ~/.bash_history || ! -e ~/.bash_history ]]; then
    echo
    echo "Unsaved, per-shell history is safer, especially for pseudo-users."
    echo -n "Do you want per-shell history? [Y/n] "
    read resp
    if [[ -z "$resp" || "$resp" == [yY]* ]]; then
	echo "# Using per-shell history (safer, especially for pseudo-users)" > ~/.bash_history
	echo "# Make this file writeable to revert to default history behavior" >> ~/.bash_history
	chmod 400 ~/.bash_history
    fi
fi

topshell=~/.bash-topshell
if [[ -e $topshell ]]; then
    echo "$topshell already present"
else
    if [[ -e ~/.bash_profile ]]; then
	(
	    set -x
	    cp -p ~/.bash_profile ~/.bash_profile.$now
	    cp -p ~/.bash_profile $topshell
	)
    elif [[ -e ~/.bash_login ]]; then
	(
	    set -x
	    cp -p ~/.bash_login $topshell
	    mv ~/.bash_login ~/.bash_login.$now
	)
    elif [[ -e ~/.profile ]]; then
	(
	    set -x
	    cp -p ~/.profile $topshell
	    mv ~/.profile ~/.profile.$now
	)
    else
	(set -x; touch $topshell)
    fi
    (set -x; ln -sf BASHRC/.bash_profile .bash_profile)
fi

pershell=~/.bash-pershell
if [[ -e $pershell ]]; then
    echo "$pershell already present"
else
    if [[ -e ~/.bashrc ]]; then
	(
	    set -x
	    cp -p ~/.bashrc ~/.bashrc.$now
	    cp -p ~/.bashrc $pershell
	)
    else
	(set -x; touch $pershell)
    fi
    (set -x; ln -sf BASHRC/.bash_profile .bashrc)
fi

for i in ~/.bash_login ~/.profile; do
    echo "Warning: unused $i present, best cleaned up" >&2
done

cat <<EOF

*********************************************************************
TRY LOGGING IN WITH THE NEW ENVIRONMENT _BEFORE_ EXITING THIS SHELL!
TO ROLL BACK:
    % rm -f .bashrc .bash_profile
    % mv .bashrc.$now .bashrc
    % mv .bash_profile.$now .bash_profile
*********************************************************************
EOF
