#!/bin/bash (just so 'file' says the right thing)

# These functions may be useful for generating prompt strings.

function _ps1_dirs {
    if [[ "${#DIRSTACK[@]}" > 1 ]]; then
	echo -n "[$((${#DIRSTACK[@]} - 1))]"
    fi
    return $1 # preserve original $?
}

# This is only used for bash versions < 4.0
function _ps1_cwd {
    typeset _trim=${PWD%/*/*/*}
    if [[ "$_trim" == "$PWD" ]]; then
	typeset _dir=$PWD
    else
	typeset _dir=${PWD/$_trim/...}
    fi
    echo -n ${_dir/$HOME/'~'}
    return $1 # preserve original $?
}

function _ps1 {
    if [[ "$BASH_VERSION" == [123]* ]]; then
	echo -n '\u@\h $(_ps1_dirs $?)$(_ps1_cwd $?) $? \#% '
    else
	echo -n '\u@\h $(_ps1_dirs $?)\w $? \#% '
    fi
}

function ps1 {
    if [[ "$1" == demo* ]]; then
	PS1='\n% '
    else
	eval PS1='$(_ps1)'
    fi
}

PROMPT_DIRTRIM=${PROMPT_DIRTRIM:-3}

# Typical usage: "source $BASHRC/func/ps1 && ps1"
